---
- name: Copy environment variables file
  template:
    src: env.j2
    dest: "{{ checkout_path }}/.env"
    mode: 0644
    owner: "{{ system_user }}"
    group: "{{ system_group }}"

- name: Install Javascript requirements
  shell: yarn install
  args:
    chdir: "{{ checkout_path }}"
  become: True
  become_user: "{{ system_user }}"

- name: Compile Javascript
  shell: yarn build
  args:
    chdir: "{{ checkout_path }}"
  become: True
  become_user: "{{ system_user }}"

- name: Make the new codebase current
  file:
    src: "{{ checkout_path }}"
    dest: "{{ codebase_path }}"
    state: link
    force: yes
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
