---
- name: Install NVM
  include_role:
    name: onai.nvm
  delegate_to: 127.0.0.1
  become_user: "{{ react_system_user }}"
  vars:
    nvm_user: "{{ react_system_user }}"
    nvm_group: "{{ react_system_group }}"
    nvm_node_version: "{{ react_nvm_node_version }}"
    nvm_install_path: "{{ react_nvm_nvm_root }}"
    nvm_node_dir: "{{ react_nvm_node_dir }}"
    nvm_npm_path: "{{ react_nvm_npm_path }}"
    nvm_version: "{{ react_nvm_version }}"

- name: Install React global packages
  npm:
    executable: "{{ react_nvm_npm_path }}"
    global: true
    name: "{{ item }}"
  delegate_to: 127.0.0.1
  become_user: "{{ react_system_user }}"
  with_items: "{{ react_system_wide_dependencies }}"

- name: Ensure required directories are present
  file:
    state: directory
    owner: "{{ react_system_user }}"
    group: "{{ react_system_group }}"
    path: "{{ item }}"
  delegate_to: 127.0.0.1
  become_user: "{{ react_system_user }}"
  when:
    - item is defined
    - item is not none
  with_items:
    - "{{ react_versioned_path }}"
    - "{{ react_checkout_path }}"
    - "{{ react_system_user_home }}/.ssh"


- name: Copy git key
  copy:
    content: "{{ react_git_key }}"
    dest: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
    owner: "{{ react_system_user }}"
    mode: 0600
  no_log: false
  register: copied_git_key_file
  delegate_to: 127.0.0.1
  become_user: "{{ react_system_user }}"
  when:
    - react_git_key is defined
    - react_git_key is not none

- name: Git clone react repo
  git:
    accept_hostkey: true
    repo: "{{ react_git_url }}"
    dest: "{{ react_checkout_path }}"
    version: "{{ react_git_version }}"
    depth: 1
    key_file: "{{ copied_git_key_file.dest | default('') }}"
  delegate_to: 127.0.0.1
  become_user: "{{ react_system_user }}"
  when:
    - react_git_key is defined
    - react_git_key is not none

- name: Remove Git Key
  file:
    state: absent
    path: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
  delegate_to: 127.0.0.1
  become_user: "{{ react_system_user }}"
  when:
    - react_git_key is defined
    - react_git_key is not none
    - react_remove_git_key
