---
- name: Add system user
  user:
    name: "{{ react_system_user }}"
    shell: /bin/bash
    group: "{{ react_system_group }}"
    append: yes
    createhome: yes

- name: Add yarn apt key
  shell: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  become: True
  become_user: root
  args:
    warn: no

- name: Add yarn to sources
  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  become: True
  become_user: root

- name: Download node
  shell: curl -sL https://deb.nodesource.com/setup_{{ react_node_version }} | sudo -E bash -
  become: True
  become_user: root
  args:
    warn: no

- name: Update apt cache
  apt:
    update_cache: "yes"

- name: Install system-wide dependencies
  apt:
    name: "{{ react_system_wide_dependencies }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Ensure required directories are present
  file:
    state: directory
    owner: "{{ react_system_user }}"
    group: www-data
    path: "{{ item }}"
  when:
    - item is defined
    - item is not none
  with_items:
    - "{{ react_versioned_path }}"
    - "{{ react_checkout_path }}"
    - "{{ react_system_user_home }}/.ssh"

- name: Git clone without key
  git:
    accept_hostkey: "yes"
    repo: "{{ react_git_url }}"
    dest: "{{ react_checkout_path }}"
    version: "{{ react_git_version }}"
    depth: 1
  become: True
  become_user: "{{ react_system_user }}"
  when:
    - react_git_key is not defined or react_git_key is none

- name: Copy git key
  copy:
    content: "{{ react_git_key }}"
    dest: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
    owner: "{{ react_system_user }}"
    mode: 0600
  no_log: False
  when:
    - react_git_key is defined
    - react_git_key is not none

- name: Git clone with key
  git:
    accept_hostkey: "yes"
    repo: "{{ react_git_url }}"
    dest: "{{ react_checkout_path }}"
    version: "{{ react_git_version }}"
    depth: 1
    key_file: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
  become: True
  become_user: "{{ react_system_user }}"
  when:
    - react_git_key is defined
    - react_git_key is not none

- name: Remove Git Key
  file:
    state: absent
    path: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
  become: True
  become_user: "{{ react_system_user }}"
  when:
    - react_git_key is defined
    - react_git_key is not none
    - react_remove_git_key == True
