---
- name: Add system user
  user:
    name: "{{ react_system_user }}"
    shell: /bin/bash
    group: "{{ react_system_group }}"
    append: true
    create_home: true
  
- name: Ensure required directories are present
  file:
    state: directory
    owner: "{{ react_system_user }}"
    group: www-data
    path: "{{ item }}"
  when:
    - item is defined
    - item is not none
  with_items:
    - "{{ react_versioned_path }}"
    - "{{ react_checkout_path }}"
    - "{{ react_system_user_home }}/.ssh"


- name: Install react pre-requisites for local deployment
  block:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: True
        cache_valid_time: 3600
    
    - name: Git clone with key
      git:
        accept_hostkey: "true"
        repo: "https://github.com/onaio/reveal-frontend.git"
        dest: "{{ react_local_checkout_path }}"
        version: "{{ react_git_version }}"
        depth: '1'
        force: True
        # key_file: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
      become: true
      delegate_to: localhost
      become_user: "{{ react_local_build_user }}"
      # when:
      #   - react_git_key is defined
      #   - react_git_key is not none
  when: " not react_remote_js_build|bool"




- name: Remote Git clone
  block:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: True
        cache_valid_time: 3600

    - name: Git clone without key
      git:
        accept_hostkey: "yes"
        repo: "{{ react_git_url }}"
        dest: "{{ react_checkout_path }}"
        version: "{{ react_git_version }}"
        depth: 1
      become: true
      become_user: "{{ react_system_user }}"
      when:
        - react_git_key is not defined or react_git_key is none

    - name: Copy git key
      copy:
        content: "{{ react_git_key }}"
        dest: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
        owner: "{{ react_system_user }}"
        mode: 0600
        
      no_log: false
      when:
        - react_git_key is defined
        - react_git_key is not none

    - name: Git clone with key
      git:
        accept_hostkey: "yes"
        repo: "{{ react_git_url }}"
        dest: "{{ react_checkout_path }}"
        version: "{{ react_git_version }}"
        depth: 1
        key_file: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
      become: true
      become_user: "{{ react_system_user }}"
      when:
        - react_git_key is defined
        - react_git_key is not none

    - name: Remove Git Key
      file:
        state: absent
        path: "{{ react_system_user_home }}/.ssh/{{ react_git_key_filename }}"
      become: true
      become_user: "{{ react_system_user }}"
      when:
        - react_git_key is defined
        - react_git_key is not none
        - react_remove_git_key
  when: "react_remote_js_build|bool"