---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-16.04
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  playbook:
    prepare: prepare.yml
  options:
    verbose: True
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
